In [23]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [24]:
df = pd.read_csv('./DATA/datasets_1067_1925_WA_Fn-UseC_-HR-Employee-Attrition.csv')

In [25]:
df.transpose()

0                       1     \
Age                                    41                      49   
Attrition                             Yes                      No   
BusinessTravel              Travel_Rarely       Travel_Frequently   
DailyRate                            1102                     279   
Department                          Sales  Research & Development   
DistanceFromHome                        1                       8   
Education                               2                       1   
EducationField              Life Sciences           Life Sciences   
EmployeeCount                           1                       1   
EmployeeNumber                          1                       2   
EnvironmentSatisfaction                 2                       3   
Gender                             Female                    Male   
HourlyRate                             94                      61   
JobInvolvement                          3                       2   
JobLevel                                2                       2   
JobRole                   Sales Executive      Research Scientist   
JobSatisfaction                         4                       2   
MaritalStatus                      Single                 Married   
MonthlyIncome                        5993                    5130   
MonthlyRate                         19479                   24907   
NumCompaniesWorked                      8                       1   
Over18                                  Y                       Y   
OverTime                              Yes                      No   
PercentSalaryHike                      11                      23   
PerformanceRating                       3                       4   
RelationshipSatisfaction                1                       4   
StandardHours                          80                      80   
StockOptionLevel                        0                       1   
TotalWorkingYears                       8                      10   
TrainingTimesLastYear                   0                       3   
WorkLifeBalance                         1                       3   
YearsAtCompany                          6                      10   
YearsInCurrentRole                      4                       7   
YearsSinceLastPromotion                 0                       1   
YearsWithCurrManager                    5                       7   

                                            2                       3     \
Age                                           37                      33   
Attrition                                    Yes                      No   
BusinessTravel                     Travel_Rarely       Travel_Frequently   
DailyRate                                   1373                    1392   
Department                Research & Development  Research & Development   
DistanceFromHome                               2                       3   
Education                                      2                       4   
EducationField                             Other           Life Sciences   
EmployeeCount                                  1                       1   
EmployeeNumber                                 4                       5   
EnvironmentSatisfaction                        4                       4   
Gender                                      Male                  Female   
HourlyRate                                    92                      56   
JobInvolvement                                 2                       3   
JobLevel                                       1                       1   
JobRole                    Laboratory Technician      Research Scientist   
JobSatisfaction                                3                       3   
MaritalStatus                             Single                 Married   
MonthlyIncome                               2090                    2909   
MonthlyRate                     

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   Age                       1470 non-null   int64 
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   object
 3   DailyRate                 1470 non-null   int64 
 4   Department                1470 non-null   object
 5   DistanceFromHome          1470 non-null   int64 
 6   Education                 1470 non-null   int64 
 7   EducationField            1470 non-null   object
 8   EmployeeCount             1470 non-null   int64 
 9   EmployeeNumber            1470 non-null   int64 
 10  EnvironmentSatisfaction   1470 non-null   int64 
 11  Gender                    1470 non-null   object
 12  HourlyRate                1470 non-null   int64 
 13  JobInvolvement            1470 non-null   int64 
 14  JobLevel                

In [27]:
df.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

In [28]:
df_obj = df.select_dtypes(exclude=['int64'])

In [29]:
df_obj.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   Attrition       1470 non-null   object
 1   BusinessTravel  1470 non-null   object
 2   Department      1470 non-null   object
 3   EducationField  1470 non-null   object
 4   Gender          1470 non-null   object
 5   JobRole         1470 non-null   object
 6   MaritalStatus   1470 non-null   object
 7   Over18          1470 non-null   object
 8   OverTime        1470 non-null   object
dtypes: object(9)
memory usage: 103.5+ KB


In [30]:
for i in df_obj.columns:
    print(f'unique values of {i} : {df[i].unique()}, {len(df[i].unique())}')

unique values of Attrition : ['Yes' 'No'], 2
unique values of BusinessTravel : ['Travel_Rarely' 'Travel_Frequently' 'Non-Travel'], 3
unique values of Department : ['Sales' 'Research & Development' 'Human Resources'], 3
unique values of EducationField : ['Life Sciences' 'Other' 'Medical' 'Marketing' 'Technical Degree'
 'Human Resources'], 6
unique values of Gender : ['Female' 'Male'], 2
unique values of JobRole : ['Sales Executive' 'Research Scientist' 'Laboratory Technician'
 'Manufacturing Director' 'Healthcare Representative' 'Manager'
 'Sales Representative' 'Research Director' 'Human Resources'], 9
unique values of MaritalStatus : ['Single' 'Married' 'Divorced'], 3
unique values of Over18 : ['Y'], 1
unique values of OverTime : ['Yes' 'No'], 2


In [31]:
df.drop(columns=['Over18'],inplace=True)

In [32]:
X  = df.drop(columns='Attrition')
y  = df['Attrition']

In [33]:
X = pd.get_dummies(df,drop_first=True)

In [34]:
y = y.map({'Yes':1, 'No':0})

In [35]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [36]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

In [37]:
def report_model(model):
    model.fit(X_train,y_train)
    model_preds = model.predict(X_test)
    print(classification_report(y_test,model_preds))
    print('\n')
    print(confusion_matrix(y_test,model_preds))
    print('\n')
    print(accuracy_score(y_test,model_preds))

In [38]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier()
report_model(model)

              precision    recall  f1-score   support

           0       0.87      0.95      0.91       416
           1       0.31      0.13      0.18        70

    accuracy                           0.83       486
   macro avg       0.59      0.54      0.54       486
weighted avg       0.79      0.83      0.80       486



[[396  20]
 [ 61   9]]


0.8333333333333334


In [39]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()
report_model(model)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       416
           1       1.00      1.00      1.00        70

    accuracy                           1.00       486
   macro avg       1.00      1.00      1.00       486
weighted avg       1.00      1.00      1.00       486



[[416   0]
 [  0  70]]


1.0


In [40]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
report_model(model)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       416
           1       1.00      1.00      1.00        70

    accuracy                           1.00       486
   macro avg       1.00      1.00      1.00       486
weighted avg       1.00      1.00      1.00       486



[[416   0]
 [  0  70]]


1.0


In [43]:
from sklearn.svm import SVC
model = SVC()
report_model(model)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       416
           1       1.00      0.99      0.99        70

    accuracy                           1.00       486
   macro avg       1.00      0.99      1.00       486
weighted avg       1.00      1.00      1.00       486



[[416   0]
 [  1  69]]


0.9979423868312757


In [44]:
#scaling data for logistic model
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [45]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
report_model(model)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       416
           1       1.00      1.00      1.00        70

    accuracy                           1.00       486
   macro avg       1.00      1.00      1.00       486
weighted avg       1.00      1.00      1.00       486



[[416   0]
 [  0  70]]


1.0
